# Generated by Django 5.2.11 on 2026-09-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_add_network_relations"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewPostAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.CharField(
                        choices=[("community", "커뮤니티"), ("network", "네트워크")],
                        max_length=20,
                    ),
                ),
                ("post_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("sending", "발송 중"),
                            ("sent", "발송 완료"),
                            ("failed", "실패"),
                            ("skipped", "건너뜀"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "새 글 메일 알림",
                "verbose_name_plural": "새 글 메일 알림",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="notificatio_status_ec1a1b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "post_id"),
                        name="uniq_new_post_alert_board_post",
                    )
                ],
            },
        ),
    ]
