# Generated by Django 5.2.11 on 2026-02-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="community/thumbnails/"
            ),
        ),
    ]
