# Generated by Django 5.2.11 on 2026-02-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_post_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
