# Generated by Django 5.2.11 on 2026-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_commentreaction_alter_reaction_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="group",
            field=models.CharField(
                choices=[
                    ("community", "커뮤니티"),
                    ("network_student", "네트워크-재학생"),
                    ("network_graduate", "네트워크-졸업생"),
                    ("network_qna", "네트워크-QNA"),
                ],
                default="community",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("slug", "group")},
        ),
    ]
