# Generated by Django 5.2.11 on 2026-02-27 16:25

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model("community", "Category")

    categories = [
        # 🔹 community
        ("공지", "notice", "community"),
        ("홍보", "promotion", "community"),
        ("알쓸잡생", "free", "community"),
        ("기타", "etc", "community"),

        # 🔹 network - 재학생
        ("인턴", "intern", "network_student"),
        ("대외활동/공모전", "activity", "network_student"),
        ("학교 프로그램", "program", "network_student"),
        ("전공(다부전공)", "major", "network_student"),
        ("국제교류", "global", "network_student"),

        # 🔹 network - 졸업생
        ("취업", "job", "network_graduate"),
        ("대학원", "gradschool", "network_graduate"),
        ("직무 알아보기", "career", "network_graduate"),

        # 🔹 network - QNA
        ("학습", "study", "network_qna"),
        ("진로", "path", "network_qna"),
        ("기타", "etc", "network_qna"),
    ]

    for name, slug, group in categories:
        Category.objects.get_or_create(
            name=name,
            slug=slug,
            group=group
        )

class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_category_group_alter_category_name_and_more"),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
