# Generated by Django 5.2.11 on 2026-02-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_seed_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
