# Generated by Django 5.2.11 on 2026-03-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0002_seed_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
