# Generated by Django 5.2.11 on 2026-03-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0005_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postfile",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="networks.post",
            ),
        ),
    ]
