# Generated by Django 5.2.11 on 2026-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0006_alter_postfile_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="image_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
