# Generated by Django 5.2.11 on 2026-02-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('user_type', models.CharField(choices=[('student', '재학생'), ('graduate', '졸업생')], max_length=10, verbose_name='사용자 유형')),
                ('student_id', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='학번')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='학년')),
                ('admission_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='입학년도(기수)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='이메일 인증 완료')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
            },
        ),
    ]
