# Generated by Django 5.2.11 on 2026-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
