# Generated by Django 5.2.11 on 2026-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="이메일 인증 완료"),
        ),
    ]
