# Generated by Django 5.2.11 on 2026-03-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_verified"),
        ("users", "0003_user_bio_user_profile_image_alter_user_is_verified"),
    ]

    operations = []
