# Generated by Django 5.2.11 on 2026-03-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20260301_0539"),
        ("users", "0004_merge_20260302_1441"),
    ]

    operations = []
