# Generated by Django 5.2.11 on 2026-03-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20260303_0449"),
        ("users", "0005_merge_20260302_1637"),
    ]

    operations = []
