# Generated by Django 5.2.11 on 2026-03-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260303_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='학과'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='온보딩 완료 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='카카오 ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_info_consent',
            field=models.BooleanField(default=False, verbose_name='개인정보 수집·이용 동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(default='email', max_length=20, verbose_name='소셜 제공자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='인증 완료'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', '재학생'), ('graduate', '졸업생')], default='', max_length=10, verbose_name='사용자 유형'),
        ),
    ]
