# Generated by Django 5.2.11 on 2026-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_add_primary_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_point_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="로그인 점수 마지막 지급일"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="score",
            field=models.PositiveIntegerField(default=0, verbose_name="활동 점수"),
        ),
    ]
