# Generated by Django 5.2.11 on 2026-03-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_last_login_point_date_user_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_type",
                    models.CharField(
                        choices=[("post_like", "게시글 좋아요"), ("comment_like", "댓글 좋아요")],
                        max_length=20,
                    ),
                ),
                ("target_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "score_type", "target_id")},
            },
        ),
    ]
