# Generated by Django 5.2.11 on 2026-03-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_delete_likescorelog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scorehistory",
            index=models.Index(
                fields=["user", "score_type"], name="users_score_user_id_e1261c_idx"
            ),
        ),
    ]
