# Generated by Django 5.2.11 on 2026-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_scorehistory_users_score_user_id_e1261c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_encrypted",
            field=models.TextField(blank=True, null=True, verbose_name="이메일(암호화)"),
        ),
        migrations.AddField(
            model_name="user",
            name="email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="이메일 해시",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name_encrypted",
            field=models.TextField(blank=True, null=True, verbose_name="이름(암호화)"),
        ),
        migrations.AddField(
            model_name="user",
            name="name_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="이름 해시",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="student_id_encrypted",
            field=models.TextField(blank=True, null=True, verbose_name="학번(암호화)"),
        ),
        migrations.AddField(
            model_name="user",
            name="student_id_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="학번 해시",
            ),
        ),
    ]
