# Generated by Django 5.2.11 on 2026-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_email_encrypted_user_email_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name_encrypted",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name_hash",
        ),
        migrations.AddField(
            model_name="studentregistry",
            name="name_encrypted",
            field=models.TextField(blank=True, null=True, verbose_name="이름(암호화)"),
        ),
        migrations.AddField(
            model_name="studentregistry",
            name="name_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="이름 해시",
            ),
        ),
        migrations.AddField(
            model_name="studentregistry",
            name="student_id_encrypted",
            field=models.TextField(blank=True, null=True, verbose_name="학번(암호화)"),
        ),
        migrations.AddField(
            model_name="studentregistry",
            name="student_id_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="학번 해시",
            ),
        ),
    ]
