# Generated by Django 5.2.11 on 2026-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_monthlywinner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="프로필 완료일시"),
        ),
        migrations.AddField(
            model_name="user",
            name="signup_landing_page",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=200,
                verbose_name="가입 유입 첫 방문 페이지",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signup_referrer",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=100,
                verbose_name="가입 유입 referrer 호스트",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signup_utm_campaign",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=100,
                verbose_name="가입 유입 utm_campaign",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signup_utm_medium",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=50,
                verbose_name="가입 유입 utm_medium",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signup_utm_source",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=50,
                verbose_name="가입 유입 utm_source",
            ),
        ),
    ]
