# Generated by Django 5.2.11 on 2026-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="target_nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
