# Generated by Django 5.2.11 on 2026-02-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', '페이지 방문'), ('post_view', '게시글 조회'), ('like', '좋아요'), ('comment', '댓글 작성'), ('signup', '회원가입'), ('login', '로그인')], max_length=30)),
                ('section', models.CharField(blank=True, choices=[('home', '홈'), ('community', '커뮤니티'), ('network', '네트워크'), ('department', '학과정보')], max_length=50, null=True)),
                ('page', models.CharField(blank=True, max_length=100, null=True)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=20, null=True)),
                ('grade_at_event', models.IntegerField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
