# Generated by Django 5.2.11 on 2026-03-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_extend_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API 에러 로그',
                'verbose_name_plural': 'API 에러 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='eventlog',
            new_name='logs_eventl_event_t_22ec3d_idx',
            old_name='logs_event_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='eventlog',
            new_name='logs_eventl_section_0949ca_idx',
            old_name='logs_section_created_idx',
        ),
        migrations.RenameIndex(
            model_name='eventlog',
            new_name='logs_eventl_post_id_c8fe1e_idx',
            old_name='logs_post_event_idx',
        ),
        migrations.RenameIndex(
            model_name='eventlog',
            new_name='logs_eventl_grade_a_7c79c9_idx',
            old_name='logs_grade_heatmap_idx',
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='author_grade_at_event',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='author_user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('page_view', '페이지 방문'), ('post_view', '게시글 조회'), ('post_create', '게시글 작성'), ('like', '좋아요'), ('comment', '댓글 작성'), ('signup', '회원가입'), ('login', '로그인'), ('search', '검색')], max_length=30),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='search_keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='apierrorlog',
            index=models.Index(fields=['created_at'], name='logs_apierr_created_c8bc6a_idx'),
        ),
        migrations.AddIndex(
            model_name='apierrorlog',
            index=models.Index(fields=['status_code'], name='logs_apierr_status__9ed851_idx'),
        ),
    ]
