# Generated by Django 5.2.11 on 2026-03-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_add_api_error_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('navigation', 'Navigation'), ('authentication', 'Authentication'), ('content', 'Content'), ('engagement', 'Engagement'), ('discovery', 'Discovery')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '이벤트 설정',
                'verbose_name_plural': '이벤트 설정',
            },
        ),
    ]
