# Generated by Django 5.2.11 on 2026-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_seed_event_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='interest_at_event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
