# Generated by Django 5.2.11 on 2026-03-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_add_interest_at_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['session_id', 'created_at'], name='logs_eventl_session_682e7b_idx'),
        ),
    ]
