# Generated by Django 5.2.11 on 2026-09-18 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_apierrorlog_response_time_ms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='활성 일자(KST)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일별 활성 사용자',
                'verbose_name_plural': '일별 활성 사용자',
                'indexes': [models.Index(fields=['date'], name='logs_dailya_date_70b5e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily_active_user_user_date')],
            },
        ),
    ]
