# Generated by Django 5.2.11 on 2026-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0009_dailyactiveuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="properties",
            field=models.JSONField(
                blank=True,
                db_default=models.Value({}, output_field=models.JSONField()),
                default=dict,
            ),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="visitor_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guest", "비로그인"),
                    ("new", "신규 회원"),
                    ("member", "기존 회원"),
                    ("returning", "휴면 복귀 회원"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "페이지 방문"),
                    ("post_view", "게시글 조회"),
                    ("post_create", "게시글 작성"),
                    ("like", "좋아요"),
                    ("comment", "댓글 작성"),
                    ("signup", "회원가입"),
                    ("login", "로그인"),
                    ("search", "검색"),
                    ("login_wall_view", "로그인 요구 화면"),
                    ("write_start", "글쓰기 시작"),
                    ("draft_save", "임시저장"),
                ],
                max_length=30,
            ),
        ),
    ]
