# Generated by Django 5.2.11 on 2026-03-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('link', models.URLField(blank=True, verbose_name='링크 URL')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('notice_type', models.CharField(choices=[('banner', '배너'), ('notice', '공지')], default='notice', max_length=20, verbose_name='유형')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='노출 시작')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='노출 종료')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사이트 공지/배너',
                'verbose_name_plural': '사이트 공지/배너',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
